pipeline {
    agent none
    options {
        // set a timeout of 20 minutes for this pipeline
        timeout(time: 20, unit: 'MINUTES')
    } //options
    stages {
        stage('execute pi job')
        agent {
            label 'base'
        } {
            steps {
                script {
                    openshift.withCluster() {
                        openshift.withProject() {
                            if (openshift.selector("jobs", "pi").exists()) {
                                openshift.selector("jobs", templateName).delete()
                            }
                            openshift.create('job', 'pi', '--image="image-registry.openshift-image-registry.svc:5000/openshift/perl" -- "perl" "-Mbignum=bpi" "-wle" "print bpi(2000)"')
                        }
                    }
                }
            }
        }
    } // stages
} // pipeline
